select * from(
select ls.id as [Lead Id],
ls.[Lead Cost],
ls.[Is Blend Lead],
ls.[Lead Source Name],
ls.[Created Date],
u.Encompass_Loan_Officer_Name__c as [Loan Officer Name],
u.Branch_Code__c as [Branch Code],
ls.[Currently Renting],
ls.[Desired Loan Amount],
ls.[Desired Rate],
ls.[Desired Rate Type],
ls.[Desired Loan Term],
ls.[Down Payment],
ls.DTI,
ls.[DTI Decision],
ls.[Existing Mortgage Balance],
ls.[Existing Mortgage Monthly Payment],
ls.[Existing Rate Type],
ls.[First Time Home Buyer],
ls.[Has Bankruptcy],
ls.[Has Foreclosure],
ls.[Intended Property Use],
ls.[Lead Type],
ls.[Desired Loan Purpose],
ls.[Is VA Eligible],
ls.[Needs Realtor],
ls.[New Home Value],
ls.[Property State],
ls.[Property City],
ls.[Preferred Language],
ls.[Quoted Rate],
ls.[Referral Source Details],
ls.[Refinance Type],
ls.[Is Self Employed],
ls.[Borrower State],
ls.[UTM Campaign],
ls.[UTM Medium],
ls.[UTM Source],
ls.[UTM Term]

from(
select l.id, 
l.Cost__c * -1 as [Lead Cost], 
case when l.Blend_Application__C is not null then 1 else 0 end as [Is Blend Lead],
s.Name as [Lead Source Name],
cast(l.CreatedDate as Date) as [Created Date], 
l.OwnerId as [Owner Id], 
CurrentlyRenting__c as [Currently Renting], 
Desired_Loan_Amount__c as [Desired Loan Amount], 
Desired_Rate__c as [Desired Rate],
Desired_Rate_Term__c as [Desired Loan Term], 
Desired_Rate_Type__c as [Desired Rate Type],
Down_Payment__c as [Down Payment],
DTI__c as [DTI],
DTI_Decision__c as [DTI Decision],
Existing_Mortgage_Balance__c as [Existing Mortgage Balance],
Existing_Mortgage_Monthly_Payment__c as [Existing Mortgage Monthly Payment],
Existing_Rate_Type__c as [Existing Rate Type],
FirstTimeHomeBuyer__c as [First Time Home Buyer],
HasBankruptcy__c as [Has Bankruptcy],
HasForeclosure__c as [Has Foreclosure],
Intended_Property_Use__c as [Intended Property Use],
l.Lead_Type__c as [Lead Type],
Ln_Type__c as [Desired Loan Purpose],
MilitaryVAEligible__c as [Is VA Eligible],
Needs_Realtor__c as [Needs Realtor],
New_Home_Value__c as [New Home Value],
Property_State__c as [Property State],
Property_City__c as [Property City],
Preferred_Language__c as [Preferred Language],
Quoted_Rate__c as [Quoted Rate],
Referral_Source_Details__c as [Referral Source Details],
Refinance_Type__c as [Refinance Type],
SelfEmployed__c as [Is Self Employed],
State as [Borrower State],
UTM_Campaign__c as [UTM Campaign],
UTM_Source__c as [UTM Source],
UTM_Term__c as [UTM Term],
UTM_Medium__c as [UTM Medium]

from Lead l

left join LeadSource s on l.Lead_Source_Name__c = s.Id

where year(l.CreatedDate) >= 2020
) ls

left join [UserQueueCombined] u on ls.[Owner id] = u.id
) lsu